export const PROVINCES_FSEARCHING = [
    'AnGiang', 'BaRiaVungTau', 'BacLieu', 'BacGiang', 'BacKan', 'BacNinh',
    'BenTre', 'BinhDuong', 'BinhDinh', 'BinhPhuoc', 'BinhThuan', 'CaMau',
    'CaoBang', 'CanTho', 'DaNang', 'DakLak', 'DakNong', 'DienBien', 'DongNai',
    'DongThap', 'GiaLai', 'HaGiang', 'HaNam', 'HaNoi', 'HaTinh', 'HaiDuong',
    'HaiPhong', 'HauGiang', 'HoaBinh', 'HungYen', 'KhanhHoa', 'KienGiang',
    'KonTum', 'LaiChau', 'LamDong', 'LangSon', 'LaoCai', 'LongAn', 'NamDinh',
    'NgheAn', 'NinhBinh', 'NinhThuan', 'PhuTho', 'PhuYen', 'QuangBinh',
    'QuangNam', 'QuangNgai', 'QuangNinh', 'QuangTri', 'SocTrang', 'SonLa',
    'TayNinh', 'ThaiBinh', 'ThaiNguyen', 'ThanhHoa', 'ThuaThienHue',
    'TienGiang', 'TraVinh', 'TuyenQuang', 'VinhLong', 'VinhPhuc', 'YenBai',
    'HoChiMinh'
];

export const PROVINCES_EN = [
    'An Giang', 'Ba Ria–Vung Tau', 'Bac Lieu', 'Bac Giang', 'Bac Kan', 'Bac Ninh',
    'Ben Tre', 'Binh Duong', 'Binh Dinh', 'Binh Phuoc', 'Binh Thuan', 'Ca Mau',
    'Cao Bang', 'Can Tho', 'Da Nang', 'Dak Lak', 'Dak Nong', 'Dien Bien', 'Dong Nai',
    'Dong Thap', 'Gia Lai', 'Ha Giang', 'Ha Nam', 'Ha Noi', 'Ha Tinh', 'Hai Duong',
    'Hai Phong', 'Hau Giang', 'Hoa Binh', 'Hung Yen', 'Khanh Hoa', 'Kien Giang',
    'Kon Tum', 'Lai Chau', 'Lam Dong', 'Lang Son', 'Lao Cai', 'Long An', 'Nam Dinh',
    'Nghe An', 'Ninh Binh', 'Ninh Thuan', 'Phu Tho', 'Phu Yen', 'Quang Binh',
    'Quang Nam', 'Quang Ngai', 'Quang Ninh', 'Quang Tri', 'Soc Trang', 'Son La',
    'Tay Ninh', 'Thai Binh', 'Thai Nguyen', 'Thanh Hoa', 'Thua Thien Hue',
    'Tien Giang', 'Tra Vinh', 'Tuyen Quang', 'Vinh Long', 'Vinh Phuc', 'Yen Bai',
    'Ho Chi Minh'
];

export const PROVINCE_MAPPING = {
    "An Giang": "AnGiang",
    "Ba Ria–Vung Tau": "BaRiaVungTau",
    "Bac Lieu": "BacLieu",
    "Bac Giang": "BacGiang",
    "Bac Kan": "BacKan",
    "Bac Ninh": "BacNinh",
    "Ben Tre": "BenTre",
    "Binh Duong": "BinhDuong",
    "Binh Dinh": "BinhDinh",
    "Binh Phuoc": "BinhPhuoc",
    "Binh Thuan": "BinhThuan",
    "Ca Mau": "CaMau",
    "Cao Bang": "CaoBang",
    "Can Tho": "CanTho",
    "Da Nang": "DaNang",
    "Dak Lak": "DakLak",
    "Dak Nong": "DakNong",
    "Dien Bien": "DienBien",
    "Dong Nai": "DongNai",
    "Dong Thap": "DongThap",
    "Gia Lai": "GiaLai",
    "Ha Giang": "HaGiang",
    "Ha Nam": "HaNam",
    "Ha Noi": "Hanoi",
    "Ha Tinh": "HaTinh",
    "Hai Duong": "HaiDuong",
    "Hai Phong": "HaiPhong",
    "Hau Giang": "HauGiang",
    "Hoa Binh": "HoaBinh",
    "Hung Yen": "HungYen",
    "Khanh Hoa": "KhanhHoa",
    "Kien Giang": "KienGiang",
    "Kon Tum": "KonTum",
    "Lai Chau": "LaiChau",
    "Lam Dong": "LamDong",
    "Lang Son": "LangSon",
    "Lao Cai": "LaoCai",
    "Long An": "LongAn",
    "Nam Dinh": "NamDinh",
    "Nghe An": "NgheAn",
    "Ninh Binh": "NinhBinh",
    "Ninh Thuan": "NinhThuan",
    "Phu Tho": "PhuTho",
    "Phu Yen": "PhuYen",
    "Quang Binh": "QuangBinh",
    "Quang Nam": "QuangNam",
    "Quang Ngai": "QuangNgai",
    "Quang Ninh": "QuangNinh",
    "Quang Tri": "QuangTri",
    "Soc Trang": "SocTrang",
    "Son La": "SonLa",
    "Tay Ninh": "TayNinh",
    "Thai Binh": "ThaiBinh",
    "Thai Nguyen": "ThaiNguyen",
    "Thanh Hoa": "ThanhHoa",
    "Thua Thien Hue": "ThuaThienHue",
    "Tien Giang": "TienGiang",
    "Tra Vinh": "TraVinh",
    "Tuyen Quang": "TuyenQuang",
    "Vinh Long": "VinhLong",
    "Vinh Phuc": "VinhPhuc",
    "Yen Bai": "YenBai",
    "Ho Chi Minh": "HoChiMinh"
};
